In [29]:
import pandas as pd
import numpy as np
url_data=pd.read_csv("C:/Work/Ques/url_interview_cleaned.csv",sep='\t', names=['label', 'url'])
url_data

      label                                                url
0         0  http://e.realscreen.com/n?_t=f&_i=gaxqvj&_ei=d...
1         0  http://rss.cnn.com/~r/rss/cnn_topstories/~3/7_...
2         0  https://sable.madmimi.com/c/132377?id=fongofag...
3         0  https://platform.mi.spglobal.com/interactivex/...
4         0  http://go.pardot.com/e/45492/mail-utm-content-...
...     ...                                                ...
10996     1  http://eproxy.pusan.ac.kr/link.n2s?url=jgfgjpj...
10997     1  http://ebm.estevenalan.com/c/tag/tbbdq5pb7rq-w...
10998     1                               http://oneratez.com/
10999     1  http://c9.io/api/nc/auth?client_id=qaazggjfrxr...
11000     1  http://c9.io/signin.html?login_hint=&pdajkgekg...

[11001 rows x 2 columns]

In [30]:
x=url_data.url
y=url_data.label

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
vector=CountVectorizer(strip_accents='unicode',stop_words='english',ngram_range=(1,1),max_df=0.95,min_df=0.01)

In [50]:
X_total=vector.fit_transform(x.values.astype('U'))

In [51]:
X_df=pd.DataFrame(X_total.toarray(),columns=vector.get_feature_names())

In [52]:
X_df

,262762,2997,4086,779,aa,abnormalsecurity,account,alerts,ana,ashx,...,store,task,thewrap,tp,tr,twitter,usr_prf_id,wd5,web,www
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [83]:
X_df.dtypes

262762        int64
2997          int64
4086          int64
779           int64
aa            int64
              ...
twitter       int64
usr_prf_id    int64
wd5           int64
web           int64
www           int64
Length: 101, dtype: object

In [53]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X_df,y,random_state=1)

In [54]:
X_train

,262762,2997,4086,779,aa,abnormalsecurity,account,alerts,ana,ashx,...,store,task,thewrap,tp,tr,twitter,usr_prf_id,wd5,web,www
1169,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9551,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4717,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7268,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8722,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7813,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
10955,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
905,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5192,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
235,0,0,0,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [66]:
X_train.dtypes

262762        int64
2997          int64
4086          int64
779           int64
aa            int64
              ...
twitter       int64
usr_prf_id    int64
wd5           int64
web           int64
www           int64
Length: 101, dtype: object

In [55]:
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

In [56]:
nb=MultinomialNB()
nb.fit(X_train,Y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [57]:
y_train_pred=nb.predict(X_train)

In [58]:
y_train_pred

array(['1', '0', '0', ..., '0', '0', '0'], dtype='<U94')

In [59]:
Y_train

1169     0
9551     0
4717     0
7268     0
8722     0
        ..
7813     0
10955    1
905      0
5192     0
235      0
Name: label, Length: 8250, dtype: object

In [60]:
y_test_pred=nb.predict(X_test)

In [93]:
y_test_pred=y_test_pred.astype(object)

In [94]:
Y_test

3380     0
10114    1
8577     0
7617     0
9229     0
        ..
8877     0
9961     0
5468     0
2910     0
7835     0
Name: label, Length: 2751, dtype: object

In [95]:
from sklearn import metrics

In [97]:
metrics.roc_auc_score(Y_test,y_test_pred)

0.8679385702907209

In [98]:
metrics.accuracy_score(Y_test,y_test_pred)

0.9687386404943656